// Search + fetch over the bundled CoW docs corpus (lib/docs-data.json,
// generated by scripts/build-docs.ts from github.com/cowprotocol/docs and
// COMMITTED so serverless needs no network). Simple term-hit ranking with a
// title boost — good enough for "how do CoW fees work" retrieval, zero deps.

export interface DocPage {
  path: string;
  title: string;
  text: string;
}

let corpus: DocPage[] | null = null;

/** Lazy-load the corpus (kept out of the module graph until first use). */
export async function loadCorpus(): Promise<DocPage[]> {
  if (!corpus) {
    const mod = (await import("./docs-data.json")) as { default: DocPage[] };
    corpus = mod.default;
  }
  return corpus;
}

/** Test seam. */
export function setCorpusForTests(pages: DocPage[] | null): void {
  corpus = pages;
}

const tokenize = (s: string): string[] =>
  s
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length >= 2);

const countHits = (haystackLower: string, term: string): number => {
  let count = 0;
  let idx = haystackLower.indexOf(term);
  while (idx !== -1 && count < 50) {
    count++;
    idx = haystackLower.indexOf(term, idx + term.length);
  }
  return count;
};

export interface SearchHit {
  path: string;
  title: string;
  score: number;
  snippets: string[];
}

function snippetsFor(text: string, textLower: string, terms: string[], max = 2): string[] {
  const out: string[] = [];
  const seen = new Set<number>();
  for (const term of terms) {
    if (out.length >= max) break;
    const idx = textLower.indexOf(term);
    if (idx === -1) continue;
    const start = Math.max(0, idx - 120);
    // Skip snippets that overlap one we already took.
    if ([...seen].some((s) => Math.abs(s - start) < 150)) continue;
    seen.add(start);
    const end = Math.min(text.length, idx + term.length + 160);
    out.push((start > 0 ? "…" : "") + text.slice(start, end).replace(/\s+/g, " ").trim() + (end < text.length ? "…" : ""));
  }
  return out;
}

export async function searchDocs(query: string, first = 5): Promise<SearchHit[]> {
  const pages = await loadCorpus();
  const terms = [...new Set(tokenize(query))];
  if (terms.length === 0) return [];

  const scored: SearchHit[] = [];
  for (const page of pages) {
    const titleLower = page.title.toLowerCase();
    const textLower = page.text.toLowerCase();
    let score = 0;
    let matchedTerms = 0;
    for (const term of terms) {
      const titleHits = countHits(titleLower, term);
      const textHits = countHits(textLower, term);
      if (titleHits + textHits > 0) matchedTerms++;
      score += titleHits * 10 + Math.min(textHits, 10);
    }
    if (score === 0) continue;
    // Prefer pages matching MORE of the query's distinct terms.
    score += matchedTerms * 25;
    scored.push({ path: page.path, title: page.title, score, snippets: snippetsFor(page.text, textLower, terms) });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, Math.min(first, 10));
}

export async function getDocPage(pathArg: string): Promise<DocPage | null> {
  const pages = await loadCorpus();
  const norm = pathArg.trim().replace(/^\/+|\/+$/g, "").replace(/\.(md|mdx)$/, "");
  return pages.find((p) => p.path === norm) ?? null;
}
